- name: Node.js | Add the node.js PPA
  action: command add-apt-repository -y ppa:chris-lea/node.js creates=/etc/apt/sources.list.d/chris-lea-node_js-trusty.list
  sudo: yes

- name: Node.js | Install nodejs and npm
  action: apt pkg={{item}} state=latest update_cache=true
  sudo: yes
  with_items:
   - nodejs