---
ufw_connection_rate_limits: [ ]
ufw_whitelisted_ipv4_addresses: [ ]
ufw_whitelisted_ipv6_addresses: [ ]
ufw_whitelisted_ports:
  -  { port: 22,  protocol: tcp }
  -  { port: 80,  protocol: tcp }
  -  { port: 3000,  protocol: tcp }
  -  { port: 1080,  protocol: tcp }
  -  { port: 1025,  protocol: smtp }
